version: '3.8'

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.armv7
    environment:
      - TZ=Europe/Berlin
    ports:
      - "4000:4000"
    volumes:
      - ./data:/usr/src/app/data
    privileged: true
