version: '3.8'

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.armv7
    env_file: application.env
    ports:
      - "4000:4000"
    volumes:
      - ./data:/usr/src/app/data
    privileged: true
